apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
  labels:
    app: course-app
data:
  LOG_LEVEL: "info"
  APP_NAME: "course-app"
  PORT: "8080"
  APP_STORE: "redis"
  APP_REDIS_URL: "redis://redis:6379"
