apiVersion: v1
kind: Service
metadata:
  name: {{ include "course-app.fullname" . }}
  labels:
    app: course-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: course-app
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
