apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-viewer
  namespace: {{ include "course-app.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: db-readonly
  namespace: {{ include "course-app.namespace" . }}
rules:
  - apiGroups:
      - dragonflydb.io
    resources:
      - dragonflies
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: db-readonly
  namespace: {{ include "course-app.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: db-readonly
subjects:
  - kind: ServiceAccount
    name: db-viewer
    namespace: {{ include "course-app.namespace" . }}
