{{- if .Values.tls.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "course-app.fullname" . }}-tls
  namespace: {{ include "course-app.namespace" . }}
  labels:
    app: course-app
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
{{- end }}
