apiVersion: v1
kind: ConfigMap
metadata:
  name: course-app-config
  labels:
    app: course-app
data:
  LOG_LEVEL: "info"
  APP_NAME: "course-app"
  PORT: "8080"
  APP_STORE: "sqlite"
  APP_DB_PATH: "data/data.sql"
