apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-app
  labels:
    app: course-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-app
  template:
    metadata:
      labels:
        app: course-app
    spec:
      containers:
        - name: course-app
          image: xcbxcbxxabzc/course-app:1.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"

