nameOverride: ""
fullnameOverride: ""

image:
  repository: xcbxcbxxabzc/course-app
  tag: "2.0"
  pullPolicy: Always

replicas: 1

service:
  type: ClusterIP
  port: 3000
  targetPort: 8080

config:
  LOG_LEVEL: info
  APP_NAME: course-app
  PORT: "8080"
  APP_STORE: redis

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 1Gi

ingress:
  enabled: true
  className: traefik
  host: course-app.local
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

tls:
  create: true
  secretName: ""
  crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURORENDQWh5Z0F3SUJBZ0lVTG9VcTVTbTRyT0tSakxaSWlyTFJFdC9UaXBrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF3d1FZMjkxY25ObExXRndjQzVzYjJOaGJEQWVGdzB5TmpBMU1ESXhOREV5TWpsYQpGdzB5TnpBMU1ESXhOREV5TWpsYU1Cc3hHVEFYQmdOVkJBTU1FR052ZFhKelpTMWhjSEF1Ykc5allXd3dnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ1RBWXJWQW9RUHlVVFpqZzVBSWphSGU2YzcKMXRZNmlCM09YMGRWUlRGa3dHbENENU42dVByWloydFJzaGw3MVRsQlpSQ1Boem15TWxJT3Zxdks1cm05MngyRApHUEY1UnZlbHJFVEtRZGVqWmswNmQ4YVN5RDZTU3lCcW1xeHg2a2owK25MSFlkZEtQeXJCQ1ZiNmRrbk50cjFXCnJ5VFlPazNFUDQ4M2NyN08zQ0dVRVRlZmpTVStmeXBkWS8vbmtBWnpNSERET3dYaENTWmtuenFhRGVFSjNGNnIKcFREZ1dkRTVlbmczaE94OFdXUG9rb1pjaGVuZC9xYVpBTDJMR04yZ1hFeW5kUTlIbVJBenNxUTk1UmtRTWxuNgowWkdWbTRQZ0EyMHZEbHI2a0VtS1NaZ0pCb1lraWJhenpEaUNnZlFiazBOalFTZ3lIS3NuRWgyR2VwakhBZ01CCkFBR2pjREJ1TUIwR0ExVWREZ1FXQkJSbDRMaUFLUUJERDlFRHJZbzcvOWVacUVLZGFUQWZCZ05WSFNNRUdEQVcKZ0JSbDRMaUFLUUJERDlFRHJZbzcvOWVacUVLZGFUQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01Cc0dBMVVkRVFRVQpNQktDRUdOdmRYSnpaUzFoY0hBdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUVDdTArZFZEaTJUCjlSYktWekxkc3VQK0d1NnllZGlKWlBOcVNBaDloTmpQV0VCdHZCWjZtMFdyN2loU2UxUlVBalBHd05KczFSS2oKV3ZlVEVmWHRreUgvcjRpQ1RGQngvZmJGZkowZ1ZJdTIwOVp0UXRZMzhPTUtBQWtIdURKc0J2ZkVLSlZRaWxsOQorVlV6YmpTRzYrWlB4aklEYlNHUHRScVQrRW8xMkxwdWJGd0dIWnhvY0tvK2E0N0M4aytINXBIRU1CUUs0UkpMCjFlelN0NkV6aERhOVgyZ1MwZlNINUN1LzYwWGVFbVlkMzVBenJ6R1dRWEtabUtMMERVTEJSb2Y5Z0U3Zll2d3MKTlUxQzdOZGQzbVJHS0dSSUtpcXU5cW9SeUpmemp5QmY2UFlTL0h5RDR1bGtmRldUbkpkYzUyTyszS3NEU25hQgo4RCs5RTFUN2tlMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ1RBWXJWQW9RUHlVVFoKamc1QUlqYUhlNmM3MXRZNmlCM09YMGRWUlRGa3dHbENENU42dVByWloydFJzaGw3MVRsQlpSQ1Boem15TWxJTwp2cXZLNXJtOTJ4MkRHUEY1UnZlbHJFVEtRZGVqWmswNmQ4YVN5RDZTU3lCcW1xeHg2a2owK25MSFlkZEtQeXJCCkNWYjZka25OdHIxV3J5VFlPazNFUDQ4M2NyN08zQ0dVRVRlZmpTVStmeXBkWS8vbmtBWnpNSERET3dYaENTWmsKbnpxYURlRUozRjZycFREZ1dkRTVlbmczaE94OFdXUG9rb1pjaGVuZC9xYVpBTDJMR04yZ1hFeW5kUTlIbVJBegpzcVE5NVJrUU1sbjYwWkdWbTRQZ0EyMHZEbHI2a0VtS1NaZ0pCb1lraWJhenpEaUNnZlFiazBOalFTZ3lIS3NuCkVoMkdlcGpIQWdNQkFBRUNnZ0VBT0lPR3hrWE4xQzNKYUtONmFnQmRHeStYeG1MY2Y2cjFYbkYxZ0Z2MTFhZzgKcnRkREdKSkZhVStmUzh4ZWpLTVhmRUxvbjJ6YWF0MTZlMDJreUg5emwzL0ZkREVpSDcvL0UzTkxETUJNTUhaegpLUStEeU1qdmVSa2xrS1grdGxwZGlzUS9YTlFKeW5MSE1tZXZSdUV6bFVCendIL2JkNzdPUjZ3eG1Cem1LcXFUClVnR2tIQlNzWHYvbkVnLzZocVdjWFI2QVhRT1VzWmc5R3BTUmtZNXBYN0gyT0pWQURSem5IQVplWm9LZmpRVW0KV3RQT2xmUnZuVXBtR0QxaGNZK0VaNmNaUXV5MDlmb0pjWEtmR044R1NnSW5uVVEyQkdTa2Fub2JGZnZRZGViVAo1OE9CZHNXSlBML25xbjZCZk1SODV3TEZYT1ZZTG9nT1FLcGRJY1UwWlFLQmdRRE9jY2VkSW01TG44S0FFSHY0CktDTitEVDdHeWcvdmpOQlI3ZUg4K2d3dHNnTTFRNWtybWcrcmFHQ01pblhVamRvVHk2YkNVemY1Nm1IMVVObXIKMmdFTTVnblNhTGJGQjkrakdtNGFCa3VVSm1TZ2ZqdXdaTyszTXFPdUJzY3A1dEYzUXZSUUhRTlJZNUowUFJqKwpzZVVINitHRHBmZ1EzV2JHa0RDRVhpU2hPd0tCZ1FDMlN6WU1MQmxzcy83NFJBWnZoTURWUDRyRThMaFZHMHZFCmx0U3cwRGNvYzd0S0ZyTGQrVEdrY0MwYThONG9ZWGl6RGpEbTJGZjhYR1JDZ0M0cUo2UW1Cdm53NDZBV2VOR1cKOTVBdXdPU25GdHpuWFRocjVCM3NsTmNXSG5Bdnhqck1EZHZQUUxXSDFrRzFzZWF2cDFtQXc4aUdxZVYxQ1ZMego4TGtoR0MwdDVRS0JnQThRUWs1MjZyRmQ4T1ZEVHFpeGpSVnZoZnNmVjFaVllnWDRZNXIvNjgrUnc2WXBUbzNkCjZmTEo1UEdjVU1pM3FRZjB2akJEdmp2Z0hGRzRHb250bUZJR253VFpXeXk1VEZvc1hZaE1tVXN3R2Z1VCttcisKa25jOW5LL2dFcnc5K1Y3SVplZEtscWxqcUpZT3R6b3VaTlhWSWxsbXpOaitMcmVpWWNmbXpxbHRBb0dBRGdocQpKN081WFZIWjNkaTJ1aHo1RHpGdUNFMFRrNUdmV29uVjQ2cVRwR3lNVFY3RDlDeDdzdEhqMXdBVnlmdis0NkhECkIvSTlpN0s5RVJWMitFM0c2QnAvWVJqVXVRWWg5RUlvZWtEbEdTdThZNThjZWNtOHQvcVpPQjJ0dXkvQ1ZQVDQKSjlNdVpqK0xIV2FOZ0pZY1lMb3hsSlE5a3EzZUVlTkZEUlFrWGpVQ2dZQk90V0pIOU94M2hXNzJ6UHdQc0E1awpqbnNqandzek9EUm5LZHVBYjBOY1NLbW10dXNvaUNyZmtYNkplYXA0NzNuSEJNYWlrNzJwT0dvV0VRemMyT05aCjl3emI2K3E0dFlOQkJqQll2R05RYzdwN21wWG5KQTl4T1JQTUZMZFM5alNUWjJVNjRuWWs1VHR0dzFKNHRUWk0KSjRabG5FWmZjdERWMFc2Y292cVkrdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
